version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    networks:
      - main-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt 
      - dhparam:/etc/ssl/certs ## open ssl generated key
    depends_on:
      - nodejs ## nodejs app service name
    networks:
      - main-network ## service's network

  certbot:
    image: certbot/certbot
    container_name: cerbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email youremail@email.com --agree-tos --no-eff-email --force-renewal -d {yourdamin.com} -d www.{yourdomain.com}

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: $PWD/web-root/views
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: $PWD/dhparam/
      o: bind

networks:
  main-network:
    driver: bridge
